---
- name: nopcommerce install
  become: yes
  hosts: appserver 
  tasks: 
    - name: getting debian packages
      ansible.builtin.get_url:
        url: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb 
        dest: /tmp/packages-microsoft-prod.deb
    - name: debian packages install
      ansible.builtin.dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install